### ISSUE TITLE
use of s.arrow with genetic data

### ISSUE THREAD

**Issue by mariposa1311** [sdray/adegraphics#1]
could be interesting to plot the mean weight of each loci.
Thank you

**Comment by sdray** [comment]
Thanks for the suggestion but I am not sure to understand what you mean. Could you give me an example. I am sure that we can achieve what you want by superposing two plots.

**Comment by mariposa1311** [comment]
The idea was to represent the mean weight of each loci on the principal axis of the PCA rather than each allele separately.  For now, it can be done using this command : 

data(nancycats)
pca1=dudi.pca(tab(nancycats, NA.method="mean", freq=TRUE), scannf=FALSE, nf=10)
Value<-apply(pca1$c1, 2, tapply, locFac(nancycats), mean)
s.label(pca1$li, clab=0)
s.arrow(Value, add.p=TRUE)

**Comment by sdray** [comment]
ok. This is done with ade4. With the new adegraphics package, you can try:

library(adegenet)
library(adegraphics)
pca1=dudi.pca(tab(nancycats, NA.method="mean", freq=TRUE), scannf=FALSE, nf=10)

# one locus per plot

s.class(pca1$c1, locFac(nancycats), col = TRUE, facets = locFac(nancycats))

# one plot with all loci

s.class(pca1$c1, locFac(nancycats), col = TRUE, ellipseSize = 0, starSize = 0)
