### ISSUE TITLE
posieig argument in the scatter function

### ISSUE THREAD

**Issue by thioulouse** [sdray/adegraphics#10]
in ?scatter :
posieig | a character value **or a two-length numeric vector** (in normalized parent coordinates npc from 0 to 1) or none value indicating the position of the eigenvalues bar plot (used in kplot.sepan, kplotsepan.coa and scatter.*).

Problem : a numeric vector of length 2 is not accepted
> scatter(pca1, posieig=c(0,0))
Error in match.arg(posieig[1], choices = c("bottomleft", "bottomright",  : 
  'arg' must be NULL or a character vector

**Comment by aursiber** [comment]
Solve in ffea03c58d305a62c8fbb3de11f737083da6ab31
