### ISSUE TITLE
adegraphics Suggests: maptools

### ISSUE THREAD

**Issue by friendly** [sdray/adegraphics#13]
You might want to follow up on the Guerry discussion by trying to remove the dependency on maptools

**Comment by sdray** [comment]
Hi Michael,
not sure to understand. I think that everything is ok with adegraphics. I need to modify adespatial (which use pointLabels from maptools).

**Comment by rsbivand** [comment]
**adegraphics** still `Suggests:` **maptools** in https://github.com/sdray/adegraphics/blob/97c490e54d14899787eff27ef317613bcb96e957/man/adeg.panel.label.Rd

**Comment by aursiber** [comment]
Solve in cc709a09a742ab6f9505623657458d76d6d5d449 and in 7cc9bf7442d826b1061f636fe076833501e8428f.
Thanks for the remind.
