### ISSUE TITLE
Bug with adegraphics et plot(statisObject, option = ...)

### ISSUE THREAD

**Issue by maxel62** [sdray/adegraphics#3]
Using the package adegraphics, it's not possible to draw a statis object like in package ade4 :  
- the _option_ option (to select which components of the plot are displayed) from the function _plot_ is no longer available 
- _plot(statisObject)_  without using the _option_ option displayed the four components but the result is less comprehensible (the fontsize of each title or each axis label is smaller than in package ade4, some graphics have disappeared, axis scale of some graphics are different...) 

Example based on `help(statis)` :
```
library(ade4)
data(jv73)
dudi1 <- dudi.pca(jv73$poi, scann = FALSE, scal = FALSE)
wit1 <- wca(dudi1, jv73$fac.riv, scann = FALSE)
kta3 <- ktab.within(wit1)
data(jv73)
statis3 <- statis(kta3, scann = FALSE)
plot(statis3, option = 3)
plot(statis3)
library(adegraphics)
plot(statis3)
plot(statis3, option = 3)
```

**Comment by aursiber** [comment]
- The _option_ argument in the _plot_ function for _statis_ objects is actually useless in _adegraphics_.
In adegraphics, graphics are objects you can store:
`  g_statis3 <- plot(statis3)`
The _plot.statis_ function creates a multiple graph (_g_statis3_). You can reach one subgraph of _g_statis3_ using _[[_ or _$_. 
For example, to extract the first subgraph, you can do `g_statis[[1]]` or `g_statis3$inter` (the subgraphs name are get by `names(g_statis3)`).

- Indeed, default graphical parameters are updated in _adegraphics_, comparing with _ade4_.
You can modify a lot of graphical parameters (for example, _psub.cex_ to update the font size of sub titles) and find several examples in the vignette of _adegraphics_.
